### ISSUE TITLE
Base init issue + Handheld disconnects after Ringtone data is sent

### ISSUE THREAD

**Issue by amooose** [joecharamut/mx240a-driver#1]
Hi, I'm having issues getting this to connect on both the new and old driver scripts.
To start, my base seems to never respond to the BaseInitPacket of `0xad, 0xef, 0x8d, 0xff` and only responds to it when adding a 0x00 to the front to make `0x00, 0xad, 0xef, 0x8d, 0xff`.

Once this packet is sent, a initreply is received fine, the ID/Name is then sent, along with the Service name and Ringtone data, however the handset sends a HandheldDisconnectedPacket as soon as this data is done. Changing the ringtones to all be mute doesn't seem to have any effect.

One issue I might suspect is perhaps the Mx240a is using the wrong driver? Windows has it set to the hidusb.sys 10.0.19041.868 driver. Is this what yours is registered to? I also had to disable the serial check within the script to have it open the device, as it reports no serial exists.
Here's my [connect log](https://github.com/joecharamut/mx240a-driver/files/7281655/connect.log.txt) if that would be of any help.

I would greatly appreciate any help, thanks

**Comment by joecharamut** [comment]
Hmm so the code I based it off of was sending the extra 0x00 byte before each packet which I thought was useless but maybe it was to get windows to cooperate somehow. I'll have to take a look some time later on why it won't pass the serial check on windows, because I mainly use linux.

**Comment by amooose** [comment]
With a bit more research I found that windows always takes the first byte of the data sent as a 'Report ID', and I believe the first byte being a 0 tell windows no Report IDs will be used, and it is chopped off before the data is sent.

Modifying this loop in base.py's _write allows it to run in windows
```
for part in parts: 
  temp = bytearray(part)
  temp.insert(0,0x00)
  part = bytes(temp)
  logger.trace(f"[SEND] {hexdump(part)}")
  self.device.write(part)
  # todo test how much to delay
  sleep(0.15)
```

I appreciate the info and help!
